### ISSUE TITLE
Dont work spigot 1.20.4

### ISSUE THREAD

**Issue by Utlamo** [BreweryTeam/BreweryRecipesAddon#1]
I Put into plugin folder BreweryX-3.1.9.jar  and BreweryX-3.1.9-Kotlin-reduced.
 I put BrewertRecipesAddon to plugins/Brewery/addons
 i can take book but when i try open nothing happen
 command to open gui give error
 
 How to install this correctly?

**Comment by ElSantoSuper** [comment]
Same issue I'm having, but I'm running Purpur 1.20.4. Collecting and using recipes works fine, and I can get the book. Can't open the book, though, and it gives this error in the console:

```
[16:39:24 ERROR]: Could not pass event PlayerInteractEvent to Brewery v3.1.9
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.GRASS
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:124) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at dev.jsinco.recipes.guis.GuiItem$Companion.getGUIItem(GuiItem.kt:124) ~[?:?]
        at dev.jsinco.recipes.guis.GuiItem$Companion.getAllGuiBorderItems(GuiItem.kt:31) ~[?:?]
        at dev.jsinco.recipes.guis.RecipeGui.<init>(RecipeGui.kt:19) ~[?:?]
        at dev.jsinco.recipes.listeners.Events.onPlayerInteract(Events.kt:73) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor555.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2175]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2005) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1376) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2175]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by szarkans** [comment]
> java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.GRASS

There's no such thing as "grass" anymore. Either "short_grass" or "tall_grass"

**Comment by ElSantoSuper** [comment]
> > java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.GRASS
> 
> There's no such thing as "grass" anymore. Either "short_grass" or "tall_grass"

Right, but I have a custom item set up for grass:

```
  grass:
    matchAny: true
    material:
      - short_grass
      - tall_grass
```
